### ISSUE TITLE
Track Course

### ISSUE THREAD

**Issue by paudyalsushan** [paudyalsushan/treehouse#2]
## TODO 
*Course Left to Complete*

- [x] this is an incomplete item
- [x] this is an incomplete item
- [x] this is an incomplete item
